genaccount/urls.py
from django.conf.urls import url

from django.views.generic.dates import ArchiveIndexView

from . import views
from .models import Account

urlpatterns=[
    #ex: /genaccount/
#    url(r'^$', views.index, name='index'),

    #ex: /genaccount/acclist/
#    url(r'^acclist/$', views.accountlist, name='accountlist'),
    
    #ex: /genaccount/acclist/5/
#    url(r'^acclist/(?P<account_id>[0-9]+)/$', views.detail, name='detail'),

    #ex: /genaccount/showaccount/1/
#    url(r'^showaccount/(?P<pk>[0-9]+)/$', views.showaccount, name='showaccount'),


    #ex: /polls/5/results/
#    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    
    #ex: /polls/5/vote/
#    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^gen/$',
        views.AccountList.as_view(),
        name='account_list'),

    url(r'^gen/archiveindex/$',
        ArchiveIndexView.as_view(model=Account, date_field="created_on"),
        name='account_list'),
    url(r'^gen/archiveweek/$',
        ArchiveIndexView.as_view(model=Account, date_field="created_on"),
        name='account_list'),
    url(r'^gen/(?P<pk>[0-9]+)/$',
        views.AccountDetail.as_view(),
        name='account_detail'),
    url(r'^gen/create/$',
        views.AccountCreate.as_view(),
        name='account_create'),
    url(r'^gen/(?P<pk>[0-9]+)/update/$',
        views.AccountUpdate.as_view(),
        name='account_edit'),
    url(r'^gen/(?P<pk>[0-9]+)/delete/$',
        views.AccountDelete.as_view(),
        name='account_delete'),
]

swiftses/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'swiftses.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^genaccount/', include('genaccount.urls', namespace="genaccount")),
    url(r'^admin/', include(admin.site.urls)),
]

admin.site.site_title = 'Swiftses Administration'
admin.site.site_header = 'Swiftses administration'

genaccount/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse


# Create your models here.

class Account(models.Model):
    ASSET = 1
    LIABILITY = 2
    EQUITY = 3
    INCOME = 4
    COST_OF_SALES = 5
    EXPENSE = 6
    OTHER_INCOME = 7
    OTHER_EXPENSE = 8
        
    TYPE_CHOICES = (
        (ASSET, 'Asset'),
        (LIABILITY, 'Liability'),
        (EQUITY, 'Equity'),
        (INCOME, 'Income'),
        (COST_OF_SALES, 'Cost of Sales'),
        (EXPENSE, 'Expense'),
        (OTHER_INCOME, 'Other Income'),
        (OTHER_EXPENSE, 'Other Expense')
    )
    
    author = models.ForeignKey('auth.User')
    
    name = models.CharField(max_length=50, unique=True, db_index=True)
    type = models.PositiveSmallIntegerField(choices=TYPE_CHOICES, blank=True)    

    comment = models.CharField(max_length=50,blank=True, null=True)
    
    balance = models.DecimalField(max_digits=10,decimal_places=2,default='0.00')

    created_on = models.DateTimeField(default=timezone.now,editable=False)
    updated_on = models.DateTimeField(default=timezone.now)
    
    
    def __str__(self):
        ASSET = 1
        LIABILITY = 2
        EQUITY = 3
        INCOME = 4
        COST_OF_SALES = 5
        EXPENSE = 6
        OTHER_INCOME = 7
        OTHER_EXPENSE = 8
            
        TYPE_CHOICES = (
            (ASSET, 'Asset'),
            (LIABILITY, 'Liability'),
            (EQUITY, 'Equity'),
            (INCOME, 'Income'),
            (COST_OF_SALES, 'Cost of Sales'),
            (EXPENSE, 'Expense'),
            (OTHER_INCOME, 'Other Income'),
            (OTHER_EXPENSE, 'Other Expense')
        )
        return str(self.type) + '-' + str(self.id) + ' ' + self.name + ' - (' + TYPE_CHOICES[self.type][1]+')'

    def get_absolute_url(self):
        return reverse('genaccount:account_detail', args=[str(self.id)])


class BasicJournal(models.Model):
    author = models.ForeignKey('auth.User')
    postdate = models.DateTimeField(default=timezone.now, help_text="When Journal was posted")

    comment = models.CharField(max_length=50,help_text="Short comment on journal action", db_index=True)
    
    created_on = models.DateTimeField(default=timezone.now,editable=False)
    updated_on = models.DateTimeField(default=timezone.now)
    
    
    def __str__(self):
        return self.comment + ' (' + str(self.id) + ')'


class JournalEntry(models.Model):
    author = models.ForeignKey('auth.User')

    basic_journal = models.ForeignKey(BasicJournal)
    
    account = models.ForeignKey('genaccount.Account', on_delete=models.PROTECT)
    
    descr = models.CharField(max_length=50, blank=True, help_text="Description of the journal transaction entry", db_index=True)

    balance = models.DecimalField(max_digits=10,decimal_places=2,default='0.00', help_text="Postive balance always debit, negative balance always credit")
    
    created_on = models.DateTimeField(default=timezone.now,editable=False)
    updated_on = models.DateTimeField(default=timezone.now)
    
    
    def __str__(self):
        return self.descr + ' (' + str(self.id) + ')'

genaccount/forms.py
from django import forms

from .models import Account

class ShowAccountForm(forms.Form):
    account = forms.ModelChoiceField(
        queryset=Account.objects.all(), label='', empty_label='',
        widget=forms.Select(
            attrs={'onchange': 'this.form.submit();',
                   'class': 'form-control account-autocomplete',
                   'placeholder': 'Jump to an Account'}),
    )

genaccount/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.views import generic

#from django.views.generic.dates import WeekArchiveView

from .models import Account, BasicJournal, JournalEntry


class AccountList(generic.ListView):
    model = Account


class AccountDetail(generic.DetailView):
    model = Account


class AccountCreate(generic.CreateView):
    model = Account
    fields = ['author', 'name', 'type', 'comment','balance','updated_on']


class AccountUpdate(generic.UpdateView):
    model = Account
    fields = ['author', 'name', 'type', 'comment','balance','updated_on']


class AccountDelete(generic.DeleteView):
    model = Account
    success_url = reverse_lazy('genaccount:account_list')


#TODO: Requires pytz to work properly. Disable USE_TZ in settings.py to allow this method to run
#FIXME: This requirement need to be fixed - 20151025
class ArticleWeekArchiveView(WeekArchiveView):
    queryset = Account.objects.all()
    date_field = "updated_on"
    week_format = "%W"
    allow_future = True


#from .forms import ShowAccountForm



#def index(request):
    #return render(request,'genaccount/index.html','')

#def accountlist(request):
    #account_list=Account.objects.all()
    #context={'account_list':account_list}
    #return render(request,'genaccount/accountlist.html',context)

#def detail(request, account_id):
    #account=get_object_or_404(Account, pk=account_id)
    #return render(request,'genaccount/detail.html',{'account':account})


#def IndexView(generic.ListView):
    #template_name = 'genaccount/index.html'
    #context_object_name = 'account_list'

    #def get_queryset(self):
        #"""Return all customer accounts."""
        #return Account.objects.all()

#def showaccount(request,pk):
    ##return render(request,'genaccount/index.html','')
    ## if this is a POST request we need to process the form data
    #if request.method=='POST':
        ## create a form instance and populate it with data from the request:
        #form=ShowAccountForm(request.POST)
        ## check whether it's valid:
        #if form.is_valid():
            ## process the data in form.cleaned_data as required
            ## ...
            ## redirect to a new URL:
            #return HttpResponseRedirect('/')

        ## if a GET (or any other method) we'll create a blank form
    #else:
        #form=ShowAccountForm()

        #return render(request,'genaccount/detail.html',{'form':form})

genaccount/templates/genaccount/account_archive.html
{% extends "genaccount/base.html" %}

{% block content %}
        <div class="entry">
            <h1>Back to <a href="{% url 'genaccount:account_list' %}">Account List</a></h1>
        </div>
{% if object_list %}
    {% for account in object_list %}
        <p> 
            {{ account.name }} 
            <a href="{% url 'genaccount:account_detail' account.pk %}">detail...</a>
        </p>
    {% endfor %}
{% else %}
        <p> No account to display </p>
{% endif %}
    <a href="{% url 'genaccount:account_create' %}">Add...</a>
{% endblock %}

genaccount/templates/genaccount/account_confirm_delete.html
{% extends "genaccount/base.html" %}

{% block content %}
        <div class="entry">
            <h1>Back to <a href="{% url 'genaccount:account_list' %}">Account List</a></h1>
        </div>

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete Account <strong>{{ object.name }}</strong>?</p>
    <input type="submit" value="yes" />
    <a href="{% url 'genaccount:account_list' %}">no</a>
</form>

{% endblock %}

genaccount/templates/genaccount/account_detail.html
{% extends "genaccount/base.html" %}

{% block content %}
        <div class="entry">
            <h1>Back to <a href="{% url 'genaccount:account_list' %}">Account List</a></h1>
        </div>
        <div class="entry">
            <h1>{{ object.name }}</h1>
            <p><em>Author: {{ object.author.username }}</em></p>
            <p>Type: {{ object.type }}</p>
            <p>Comment: {{ object.comment }}</p>
            <p>Balance: {{ object.balance }}</p>
        </div>
        <div class="entry">
            <a href="{% url 'genaccount:account_edit' object.pk %}">Edit</a>
        </div>
        <div class="entry">
            <a href="{% url 'genaccount:account_delete' object.pk %}">Delete</a>
        </div>

{% endblock %}

genaccount/templates/genaccount/account_form.html
{% extends "genaccount/base.html" %}

{% block content %}
        <div class="entry">
            <h1>Back to <a href="{% url 'genaccount:account_list' %}">Account List</a></h1>
        </div>
    {% if object %}
        <div class="entry">
            <h2>Edit {{ object.name }}</h2>
    {% else %}
            <h2>Create</h2>
    {% endif %}
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" />
            </form>
        </div>
{% endblock %}

genaccount/templates/genaccount/account_list.html
{% extends "genaccount/base.html" %}

{% block content %}
        <div class="entry">
            <h1>Back to <a href="{% url 'genaccount:account_list' %}">Account List</a></h1>
        </div>
{% if object_list %}
    {% for account in object_list %}
        <p> 
            {{ account.name }} 
            <a href="{% url 'genaccount:account_detail' account.pk %}">detail...</a>
        </p>
    {% endfor %}
{% else %}
        <p> No account to display </p>
{% endif %}
    <a href="{% url 'genaccount:account_create' %}">Add...</a>
{% endblock %}

genaccount/templates/genaccount/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	<title>Easy Accounting v0.1</title>
    
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    
    <!-- Fontstyles -->  
    <link href="http://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    
	<!-- Optional theme -->
    <link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}">
    <link rel="stylesheet" href="{% static "css/genaccount.css" %}">


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>

    <!-- START OF VIEW -->

    <div class="page-header">
        <h1><a href="">Easy Accounting v0.1</a></h1>
    </div>

    <div class="content-container">
        <div class="row">
            <div class="col-md-8">
{% if error_message %}
        <div class="error">
            <p><strong>{{error_message}}</strong></p>
        </div>
{% endif %}
            {% block content %}
            {% endblock %}
            </div>
        </div>
    </div>
    <div class="page-footer">
        <p>Created by SWIFT SES (Pty) Ltd</p>
    </div>
  </body>
</html>